### ISSUE TITLE
Run all simulations even if first one fails

### ISSUE THREAD

**Issue by roikonen** [lkishalmi/gradle-gatling-plugin#50] opened 2017-10-18 12:03 UTC
I have two simulations that I am running. Sometimes the first simulation does not meet the assertion criteria:
"Global: 99th percentile of response time is less than 1000 : false"

That fails the simulation and the latter simulation is not ran at all. It would be nice to know the result of the latter simulation as well even though the first one would fail. I think currently there is no way to make the testing continue if some scenarios fail in the middle.

**Comment by dosomecoding** [comment] 2018-03-08 09:47
This is a must have functionality for load testing tool. I am stuck as well.

**Comment by rooeque** [comment] 2018-04-24 20:52
Yup my team would like to use this plugin for daily regression testing, so we would like to run all the simulations. Any eta or whether or not this will be addressed?

**Comment by eshepelyuk** [comment] 2018-04-25 15:24
@rooeque current we're not having enough time to work on this. 

Are you interested in providing a PR ? I can assist you with any sort of questions.

**Comment by eshepelyuk** [comment] 2018-04-25 20:04
@roikonen @rooeque @dosomecoding - can you test and feedback about this custom build ?

[gradle-gatling-plugin-0.7.2.zip](https://github.com/lkishalmi/gradle-gatling-plugin/files/1948660/gradle-gatling-plugin-0.7.2.zip)

**Comment by rooeque** [comment] 2018-04-26 00:12
Did a simple test so far. We have a wrapper around some gatling simulations as part of our framework. I purposely set some simulations to fail, and looks like all of them ran and were recorded. Looks good!

**Comment by eshepelyuk** [comment] 2018-04-26 04:38
@rooeque That's good. I'd ask @lkishalmi to release a new version soon. 

Although I'll keep this issue open until implement proper testing for this feature.

Another thing - could you run build with `--stacktrace` flag and send me final error logs of the build.
I'd like to check if how exceptino looks on real data, is it clear for understanding the build failure reason.

**Comment by rooeque** [comment] 2018-04-26 16:51
@eshepelyuk uploaded a build scan here: https://scans.gradle.com/s/6wf3gwgyeqk34/

**Comment by eshepelyuk** [comment] 2018-04-26 18:25
Fix is merged, waiting for new release. @rooeque thank for your help

**Comment by rooeque** [comment] 2018-04-26 18:48
yup, exception looks fine to me. thanks for the quick turnaround

**Comment by eshepelyuk** [comment] 2018-04-26 19:47
Enjoy fresh 0.7.3 :)

**Closed** 2018-04-26 19:50 UTC
