### ISSUE TITLE
Installation trouble with 0.5.0: jar and pom not available  in https://plugins.gradle.org/m2

### ISSUE THREAD

**Issue by cyfax** [lkishalmi/gradle-gatling-plugin#43] opened 2017-09-14 15:05 UTC
When using this configuration [as described here:](https://plugins.gradle.org/plugin/com.github.lkishalmi.gatling/0.5.0)
`
plugins {
  id "com.github.lkishalmi.gatling" version "0.5.0"
}
`

I get this error message:
```
Executing command: "tasks"

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Gatling'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find gradle.plugin.com.github.lkishalmi.gradle:gradle-gatling-plugin:0.5.0.
     Searched in the following locations:
         https://plugins.gradle.org/m2/gradle/plugin/com/github/lkishalmi/gradle/gradle-gatling-plugin/0.5.0/gradle-gatling-plugin-0.5.0.pom
         https://plugins.gradle.org/m2/gradle/plugin/com/github/lkishalmi/gradle/gradle-gatling-plugin/0.5.0/gradle-gatling-plugin-0.5.0.jar
     Required by:
         project :
```

Indeed, when I try to download manually : 

https://plugins-artifacts.gradle.org/gradle.plugin.com.github.lkishalmi.gradle/gradle-gatling-plugin/0.5.0/7eb863ee582d3f0448cb1c31b35a485220829ff2b3bdeb2687af25ddccb05a5b/gradle-gatling-plugin-0.5.0.jar

I get:

```
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>gradle.plugin.com.github.lkishalmi.gradle/gradle-gatling-plugin/0.5.0/7eb863ee582d3f0448cb1c31b35a485220829ff2b3bdeb2687af25ddccb05a5b/gradle-gatling-plugin-0.5.0.jar</Key>
  <RequestId>724CB37EE0DD4D1B</RequestId>
  <HostId>yfIG/fPYHItfFMJZ749ylj5FcC33mxT/UU4EN4HcbVajFkP+Vh8i3ltYbMbEtG59ECkIgqQ781A=</HostId>
</Error>
```

**Comment by eshepelyuk** [comment] 2017-09-16 05:16
May you attach sample project that is reproducing the issue ?

**Comment by atomfrede** [comment] 2017-09-18 06:50
Same for me. First I thought it might take some time until the binaries are available, but it seems something else is wrong.

**Comment by cyfax** [comment] 2017-09-19 00:28
Well that is pretty simple.

`build.gradle` only consist of :
```
plugins {
  id "com.github.lkishalmi.gatling" version "0.5.0"
}
```

then run :
```
gradle tasks
```

You would get this error message:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Gatling'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find gradle.plugin.com.github.lkishalmi.gradle:gradle-gatling-plugin:0.5.0.
     Searched in the following locations:
         https://plugins.gradle.org/m2/gradle/plugin/com/github/lkishalmi/gradle/gradle-gatling-plugin/0.5.0/gradle-gatling-plugin-0.5.0.pom
         https://plugins.gradle.org/m2/gradle/plugin/com/github/lkishalmi/gradle/gradle-gatling-plugin/0.5.0/gradle-gatling-plugin-0.5.0.jar
     Required by:
         project :
```

And when you click on this link (taken from error message just above):
https://plugins.gradle.org/m2/gradle/plugin/com/github/lkishalmi/gradle/gradle-gatling-plugin/0.5.0/gradle-gatling-plugin-0.5.0.jar

which gives you:

```
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>gradle.plugin.com.github.lkishalmi.gradle/gradle-gatling-plugin/0.5.0/7eb863ee582d3f0448cb1c31b35a485220829ff2b3bdeb2687af25ddccb05a5b/gradle-gatling-plugin-0.5.0.jar</Key>
  <RequestId>724CB37EE0DD4D1B</RequestId>
  <HostId>yfIG/fPYHItfFMJZ749ylj5FcC33mxT/UU4EN4HcbVajFkP+Vh8i3ltYbMbEtG59ECkIgqQ781A=</HostId>
</Error>
```

That's all.

**Comment by cyfax** [comment] 2017-09-19 00:29
Oops. Closed accidentally.

**Comment by slovdahl** [comment] 2017-09-19 12:49
I noticed that there's a 0.5.0.1 version available now, but I still can't fetch the plugin.

**Comment by eshepelyuk** [comment] 2017-09-28 06:24
Hi all, unfortunately @lkishalmi still fighting with publishing new plugin version. Sorry for this delay.

**Comment by laci0725** [comment] 2017-10-09 14:16
Hi,
I have the same issue.
Did you find any solution?

**Comment by eshepelyuk** [comment] 2017-10-09 14:55
AFAIK - not yet :(

**Comment by eshepelyuk** [comment] 2017-10-09 14:55
AFAIK - not yet :(

**Comment by moritzzimmer** [comment] 2017-10-10 12:56
My workaround: building this plugin locally using `2.12.3` as the default scala version in `GatlingPluginExtension`. Until a fix will be available I'll include the resulting jar in my target projects git applying it like this:

```groovy

//workaround till https://github.com/lkishalmi/gradle-gatling-plugin/issues/43 is solved
buildscript {
    dependencies {
        classpath files('gradle/gradle-gatling-plugin.jar')
    }
}
apply plugin: com.github.lkishalmi.gradle.gatling.GatlingPlugin 
// end workaround

```

**Comment by eshepelyuk** [comment] 2017-10-10 20:37
`0.7.0` release, guyz could you plz try ?

**Comment by KramKroc** [comment] 2017-10-10 20:50
```
Parallel execution with configuration on demand is an incubating feature.
Download https://plugins.gradle.org/m2/gradle/plugin/com/github/lkishalmi/gatling/gradle-gatling-plugin/0.7.0/gradle-gatling-plugin-0.7.0.pom
Download https://plugins.gradle.org/m2/gradle/plugin/com/github/lkishalmi/gatling/gradle-gatling-plugin/0.7.0/gradle-gatling-plugin-0.7.0.jar

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/markcorkery/workspace/microservices-common/mvp-gatling-test/build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'com.github.lkishalmi.gatling', version: '0.7.0']
> Failed to apply plugin [id 'com.github.lkishalmi.gatling']
   > Could not create task of type 'GatlingRunTask'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

**Comment by eshepelyuk** [comment] 2017-10-10 20:51
Could you plz send sample project that can help us reproduce the issue ?

**Comment by slovdahl** [comment] 2017-10-11 05:02
Thanks, 0.7.0 works fine!

**Comment by atomfrede** [comment] 2017-10-11 05:13
I can confirm `0.7.0` works fine. Thanks!

**Comment by eshepelyuk** [comment] 2017-10-11 05:31
@cyfax @moritzzimmer could you confirm ?

**Comment by laci0725** [comment] 2017-10-11 08:43
Thanks, 0.7.0 works fine!

**Comment by moritzzimmer** [comment] 2017-10-11 09:10
@eshepelyuk I had to set 

```groovy
gatling {
    scalaVersion = '2.12.3'
}
```

(which should be the default to be compatible with gatling 2.3.0 as described in the readme.md) to fix the scala compiler errors. Seems like the default in GatlingPluginExtension is wrong (2.11.8). Without changing the scala version I get

```
Exception in thread "main" java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
        at io.gatling.core.cli.CommandLineConstant.<init>(CommandLineConstant.scala:18)
        at io.gatling.app.cli.CommandLineConstants$.<init>(CommandLineConstants.scala:21)
        at io.gatling.app.cli.CommandLineConstants$.<clinit>(CommandLineConstants.scala)
        at io.gatling.app.cli.ArgsParser$$anon$1.<init>(ArgsParser.scala:29)
        at io.gatling.app.cli.ArgsParser.<init>(ArgsParser.scala:27)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:42)
        at io.gatling.app.Gatling$.main(Gatling.scala:35)
        at io.gatling.app.Gatling.main(Gatling.scala)
```

**Comment by eshepelyuk** [comment] 2017-10-11 09:44
@moritzzimmer could you create an extract from your app that can reproduce the issue.
I'd like to invest some time into improving our functional tests so those bugs will be discovered earlier.
Right now I can't reproduce it

**Comment by atomfrede** [comment] 2017-10-11 09:54
My config doesn't set the scala version and it works fine (or I am not using any special things in my simulation):
```gradle
gatling {
    toolVersion = '2.3.0'
    simulations = {
        include "**/*Simulation.scala"
    }
}
```

**Comment by eshepelyuk** [comment] 2017-10-11 09:56
@atomfrede you also may omit `toolVersion`, it's set by plugin.

**Comment by atomfrede** [comment] 2017-10-11 09:57
yes. didn't update that yet.

**Comment by moritzzimmer** [comment] 2017-10-11 10:03
@eshepelyuk I could reproduce the problem using this build file (using 4.2 wrapper):

```groovy
plugins {
    id 'idea'
//    id 'org.springframework.boot' version '1.5.7.RELEASE'
    id "com.github.lkishalmi.gatling" version "0.7.0"
}

sourceCompatibility = JavaVersion.VERSION_1_8

repositories {
    jcenter()
}

idea {
    module {
        testSourceDirs += project.file('src/gatling/simulations')
        scopes.TEST.plus += [project.configurations.gatlingCompile]
        scopes.TEST.plus += [project.configurations.gatlingRuntime]
    }
}

gatling {
//    scalaVersion = '2.12.3'
}
```
uncommenting the spring boot plugin leads to the compiler error for me which can be fixed uncommenting the scala version.

Without the `org.springframework.boot` plugin dependency resolution seems to work fine as well:
```
\--- org.scala-lang:scala-library:2.11.8 -> 2.12.3
```
compared to
```
\--- org.scala-lang:scala-library:2.11.8
```
with enabled plugin

**Comment by atomfrede** [comment] 2017-10-11 11:54
Ah so Spring Boot interferes here somehow.

**Comment by KramKroc** [comment] 2017-10-11 12:17
@eshepelyuk sorry for the delay. My build.gradle looks like this:

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.com.github.lkishalmi.gatling:gradle-gatling-plugin:0.7.0"
  }
}

apply plugin: "com.github.lkishalmi.gatling"
```

Stacktrace:

```
./gradlew gatlingRun --stacktrace
Parallel execution with configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/xxxxxxxxxx/build.gradle' line: 12

* What went wrong:
A problem occurred evaluating root project 'xxxxxxxxxx'.
> Failed to apply plugin [id 'com.github.lkishalmi.gatling']
   > Could not create task of type 'GatlingRunTask'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'xxxxxxxxxx'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:176)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:181)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:36)
        at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:161)
        at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:158)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:158)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'com.github.lkishalmi.gatling']
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:155)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:44)
        at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
        at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
        at build_4e64iq8t8pij7m531cdvvts7f.run(/Users/xxxxxxxxxx/build.gradle:12)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        ... 61 more
Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'GatlingRunTask'.
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:123)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:118)
        at org.gradle.util.GUtil.uncheckedCall(GUtil.java:402)
        at org.gradle.api.internal.AbstractTask.injectIntoNewInstance(AbstractTask.java:178)
        at org.gradle.api.internal.project.taskfactory.TaskFactory.create(TaskFactory.java:118)
        at org.gradle.api.internal.project.taskfactory.TaskFactory.createTask(TaskFactory.java:77)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.createTask(AnnotationProcessingTaskFactory.java:46)
        at org.gradle.api.internal.project.taskfactory.DependencyAutoWireTaskFactory.createTask(DependencyAutoWireTaskFactory.java:39)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:76)
        at org.gradle.api.tasks.TaskContainer$create.call(Unknown Source)
        at com.github.lkishalmi.gradle.gatling.GatlingPlugin.createGatlingTask(GatlingPlugin.groovy:44)
        at com.github.lkishalmi.gradle.gatling.GatlingPlugin.createGatlingTask(GatlingPlugin.groovy)
        at com.github.lkishalmi.gradle.gatling.GatlingPlugin$createGatlingTask$0.callCurrent(Unknown Source)
        at com.github.lkishalmi.gradle.gatling.GatlingPlugin.apply(GatlingPlugin.groovy:31)
        at com.github.lkishalmi.gradle.gatling.GatlingPlugin.apply(GatlingPlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
        at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:139)
        ... 71 more
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'classesDirs' for gatling classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.
        at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:85)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:62)
        at org.gradle.api.internal.tasks.DefaultSourceSetOutput_Decorated.getProperty(Unknown Source)
        at com.github.lkishalmi.gradle.gatling.GatlingRunTask.<init>(GatlingRunTask.groovy:19)
        at com.github.lkishalmi.gradle.gatling.GatlingRunTask_Decorated.<init>(Unknown Source)
        at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:56)
        at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:121)
        ... 88 more


BUILD FAILED
```

**Comment by KramKroc** [comment] 2017-10-11 12:22
```
./gradlew --version

------------------------------------------------------------
Gradle 3.3
------------------------------------------------------------

Build time:   2017-01-03 15:31:04 UTC
Revision:     075893a3d0798c0c1f322899b41ceca82e4e134b

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Mac OS X 10.12.6 x86_64
```

**Comment by KramKroc** [comment] 2017-10-11 13:02
Jumoed to Gradle 4.2 and it works now. Should add a note to that affect on project page.

**Comment by eshepelyuk** [comment] 2017-10-11 13:09
OK, the reason is clear now. I'll try to upload fix soon.

**Comment by eshepelyuk** [comment] 2017-10-11 15:27
@moritzzimmer @KramKroc brand new `0.7.1` is released - plz give it a try

**Comment by KramKroc** [comment] 2017-10-12 07:30
@eshepelyuk confirm that 0.7.1 works with gradle 3.3. :shipit:

**Comment by eshepelyuk** [comment] 2017-10-12 08:04
Since initial issue (plugin publishing) is resolved now - closing this ticket.
Please create new ones for other problem.

**Closed by eshepelyuk** 2017-10-12 08:04 UTC
