### ISSUE TITLE
"compile" scope dependencies are not added to Gatling simulation run ("gatlingRun" task)

### ISSUE THREAD

**Issue by alexeyOnGitHub** [lkishalmi/gradle-gatling-plugin#36] opened 2016-12-01 01:54 UTC
hi! not sure if this is intentional... I see this in the README:

> By default plugins adds gatling libraries and project’s classes and tests classes to gatlingCompile configurations Additional dependencies can be added by plugin’s users.

what about project *libraries*? 
I had a library added to the project with "compile" scope. it works in IDEA, but "./gradlew  gatlingRun-MySimulation" gives "class not found" exception for a class from that library.
I can fix this by duplicating the same library declaration in "compile" and "gatlingRuntime" scopes, but I hope there is a better way.

**Comment by eshepelyuk** [comment] 2016-12-01 05:31
Do you have the same error if trying to run all simulations at once ?

**Comment by eshepelyuk** [comment] 2016-12-01 06:15
Ok, confirming that libraries are not included.
Though, I am not 100% sure that automatically adding all `compile` and `runtime` jars is a good idea.
I'd like to introduce a new flag instead, to conditionally append classes and libraries to `gatling` configuration.

**Comment by alexeyOnGitHub** [comment] 2016-12-01 07:14
if those libraries were required to compile the app, there is a high chance they are required to run it, so I would add them by default. do you see an example where that would be a problem?

**Comment by eshepelyuk** [comment] 2016-12-01 17:04
I don't understand your point, unfortunately.
I don't see any good reason to use all jars that are used to build an application for compiling performance tests for that application.
Those are completely different project with separate purpose, source code and dependencies.

Although, I agree that we can introduce a flag to add produce jars to `gatling` configuration.
It's a simple change, feel freelancer to provides a PR.

**Comment by alexeyOnGitHub** [comment] 2016-12-01 21:20
our Gatling tests are in a separate Git repo. they have their own Gradle project that only includes dependencies required for these L&P tests. 

the application under test lives in a separate repo and may be using any language and/or build system.

this is a typical setup that I see in other places. L&P tests are separate from the actual app.
thus, the L&P project only includes dependencies required to compile and run these tests.

**Comment by eshepelyuk** [comment] 2016-12-01 22:52
_L&P_ is load and performance, correct?
If so, then I still don't see your problem with dependencies declaration.
Declare your dependencies under `gatling` configuration, so they will be available both in compile and runtime.

**Comment by alexeyOnGitHub** [comment] 2016-12-02 01:41
I tried "gatling" scope but IDEA 2016.3 did not pick those up and thus I got compile errors (class not found). I suppose "gatling" deps scope is only known to the Gatling  Plugin and not to IDEA.

**Comment by eshepelyuk** [comment] 2016-12-02 01:47
Ok, does it works from command line ? I.e. when calling `gradle` targets from command line without IDEA ?

**Comment by alexeyOnGitHub** [comment] 2016-12-02 20:56
nope. I just changed a "compile" dependency to be "gatling" scope and ran "gradle build". got various "class not found" errors.
changed "gatling" scope back to "compile" and the build succeeded.

**Comment by eshepelyuk** [comment] 2016-12-03 07:28
Well, that's weird. We have functional tests that cover such scenarios and I supposed the only problem was in IDEA. So, may you create a dummy project with minimal data from your current project, so the issue can be reproduced there and attach to the issue.

**Comment by alexeyOnGitHub** [comment] 2016-12-08 21:13
note - I'm using Gradle 3.1. maybe that is important...

**Comment by eshepelyuk** [comment] 2016-12-09 06:24
I'm afraid I can't help you more without being able to examine project's structure :(

**Comment by alexeyOnGitHub** [comment] 2016-12-10 00:28
[gatling.zip](https://github.com/lkishalmi/gradle-gatling-plugin/files/643461/gatling.zip)

here is the most basic project that has "gatling" scope dependencies. 
running 
`gradle gatlingRun-com.mypackage.MySimulation`
gives a bunch of compilation errors.

> projects/gatling/src/test/scala/com/mypackage/MySimulation.scala:4: object google is not a member of package com
> import com.google.gson.{Gson, JsonObject}
>            ^
> projects/gatling/src/test/scala/com/mypackage/MySimulation.scala:7: object http is not a member of package org.apache
> import org.apache.http.client.methods.HttpGet
>                   ^
> projects/gatling/src/test/scala/com/mypackage/MySimulation.scala:8: object http is not a member of package org.apache
> import org.apache.http.impl.client.HttpClientBuilder
>      
>

**Comment by eshepelyuk** [comment] 2016-12-10 05:53
1. The issue is exactly the same as you've already reported in other bug. 
It's related to wrong directory structure.
See [my comment](https://github.com/lkishalmi/gradle-gatling-plugin/issues/16#issuecomment-210608728)

1. Additionally, there absolutely no need to declare `Gatling` dependencies in build script. They are automatically applied by plugin. All you need is 

```
dependencies {                                             
    gatling 'com.google.code.gson:gson:2.8.0'              
}                                                          
```

**Comment by eshepelyuk** [comment] 2016-12-11 08:32
We've recently improved `README` page. Hope it's much helpful and clear now. Please, give it a try :)

**Comment by eshepelyuk** [comment] 2016-12-15 21:22
So, any news on this ?

**Comment by alexeyOnGitHub** [comment] 2016-12-20 02:30
basically if I want to use "src/test/scala" location then I have to duplicate dependencies in "compile" and "gatling" scopes, right? and I can only rely entirely on "gatling" scope if I move all code to "src/gatling"

**Comment by eshepelyuk** [comment] 2016-12-20 06:36
This plugin imposes certain directory layout. To leverage all the functionality and defaults provided by plugin you have to strictly follow that.

If you're in situation where you need to use different folder structure I'd recommend not to rely on this plugin at all. Instead, configure required dependencies manually, so you can reach desired flexibility.

**Comment by eshepelyuk** [comment] 2016-12-28 22:55
So, may you close the issue now ?

**Comment by alexeyOnGitHub** [comment] 2016-12-28 23:59
Yes, sure

**Closed** 2017-10-10 20:31 UTC
