### ISSUE TITLE
Netty version is broken by io.spring.dependency-management SpringBoot plugin 

### ISSUE THREAD

**Issue by bguedel** [lkishalmi/gradle-gatling-plugin#53] opened 2018-04-04 03:03 UTC
When using this with springboot 2, the version of netty is updated to `4.1.22.Final`

This causes an error to be thrown
```
WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by org.asynchttpclient.netty.request.NettyRequestSender$1.operationComplete()
java.lang.NoSuchMethodError: io.netty.channel.DefaultChannelId.newInstance()Lio/netty/channel/DefaultChannelId;
```

I found to ~~fix~~ work around for this, you can force the version of netty to the version `gattling:2.3.0` wants.

```gradle
configurations.all {
    resolutionStrategy {
        eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'io.netty') {
                details.useVersion "4.0.51.Final"
            }
        }
    }
}
```

The running app still seems to run just fine.

**Comment by bguedel** [comment] 2018-04-04 03:04
This issue is not for this project, but someone using this project and the latest springboot might run into this issue.

Hope this helps.

**Comment by eshepelyuk** [comment] 2018-04-04 07:02
@bguedel I'm reopening the issue since I believe this can and should be fixed from plugin's size.
The plugin uses dedicated Gradle configuration, so theoretically it should not depend on complie configuraiton (i.e. entty from spring boot)

To better debug this, may you attach an project sample where the issue can be reproduced ? this helps me to find potential fix much faster. 

thanks in advance

**Comment by bguedel** [comment] 2018-04-04 14:08
Link to my project with this implemented.
The username is different, but thats b/c i noticed i was signed into the wrong one when i made the initial issue.
https://github.com/wsguede/gatling

**Comment by eshepelyuk** [comment] 2018-04-04 14:10
I assume i just have to execute  ?

    $ ./gradlew gatlingRun

**Comment by bguedel** [comment] 2018-04-04 14:35
deploy the original app first, then run gatlinRun

Terminal 1
```sh
./gradlew bootRun
```

Terminal 2
```sh
./gradlew gatlingRun
```

**Comment by eshepelyuk** [comment] 2018-04-04 14:57
Thank you very much for the help. Hope to resolve this soon :)

**Comment by eshepelyuk** [comment] 2018-04-26 20:12
@bguedel I'm closing the issue, since it's not easy to automatically detect and fix such projects.
Here's [README update](https://github.com/lkishalmi/gradle-gatling-plugin#spring-boot-and-netty-version) for workaround

**Closed** 2018-04-26 20:13 UTC
Labels: bug

**Comment by saeedansari** [comment] 2018-07-23 17:13
@eshepelyuk I have the same issue, but my project is a maven project. Should I remove all transitive netty libraries and include them specifically with the version above?

**Comment by dhaval201279** [comment] 2019-02-20 16:01
@eshepelyuk Any pointers regarding how to do similar exclusion to maven based project

**Comment by iwejay** [comment] 2019-06-18 09:32
@dhaval201279   desired version can be specified in PoM as below

`<properties>
    <netty.version>4.0.51.Final</netty.version>
</properties>`

**Comment by zorglub76** [comment] 2020-07-28 07:19
I'm a confused noob.
I tried `ext['netty.version'] = '4.0.51.Final'`, but the netty version was still the latest.
I tried the code at the beginning of this thread, but Gradle wasn't able to find netty-handler-proxy-4.0.51.Final.pom, which is required by project : > io.gatling.highcharts:gatling-charts-highcharts:3.3.1 > io.gatling:gatling-http-client:3.3.1
I tried DependencyManagement solution, but it wasn't recognized by gradle. Then I found out that I need some plugin for it to work, and after including it, I wasn't sure where should I put my 
`dependencies {
    compile group: 'org.scala-lang', name: 'scala-library', version: "$scalaPluginVersion"
}`

Is there an example build for the minimal setup?

**Comment by slandelle** [comment] 2020-07-28 12:30
Netty 4.0 has reached end of life more than 2 years ago (latest release was feb 2018). Gatling and Spring Boot modern versions both require Netty 4.1.
The best thing you should do would be to upgrade your application to a supported Spring version.
If your organization doesn’t see the point of maintaining their stack (cf Equifax story), you’ll have to move your Gatling code to a different repository/Gradle project so you don’t have such classpath clash.

**Comment by zorglub76** [comment] 2020-07-28 12:43
I'm not using any application - the tests are standalone, and I'm using this in configuration 
`plugins {
    id "com.github.lkishalmi.gatling" version "3.3.4"
}

group 'com.faxi.gatling'
version '1.0-SNAPSHOT'

repositories {
    jcenter()
}
gatling {
    simulations = { include "**/api/Organisation.scala" }
    includeMainOutput = false
    includeTestOutput = false
}`


The test "Organisation.scala" imports only these:
`package api

import java.text.SimpleDateFormat
import java.util.Calendar

import io.gatling.core.Predef._
import io.gatling.http.Predef._

class Organisation extends Simulation {`

**Comment by slandelle** [comment] 2020-07-28 12:55
@zorglub76 then why are you highjacking a Spring Boot related issue if you’re not using Spring Boot?!
Gatling modern versions require Netty 4.1, don’t try to downgrade to Netty 4.0, it won’t work.

**Comment by zorglub76** [comment] 2020-07-28 13:14
Argh... Sorry for highjacking the thread. Now I see that the error reported here is different to what I have (it's Netty in both cases, but mine is `java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled`).

**Comment by slandelle** [comment] 2020-07-28 13:15
It’s not an ERROR but just a DEBUG log.

**Comment by eshepelyuk** [comment] 2020-07-28 13:45
Apparently, no new issues here ?

**Comment by zorglub76** [comment] 2020-07-28 13:46
Yeah, it's ok. Sorry again, and thanks for the suppor!
