### ISSUE TITLE
Could not resolve all dependencies for 0.5.0 and 0.5.0.1 plugin version

### ISSUE THREAD

**Issue by marcincharezinski** [lkishalmi/gradle-gatling-plugin#45] opened 2017-10-10 13:46 UTC
Hi
I'd like to bump up gradle plugin version, but I get this error. 0.4.1 version works fine. I followed this doc https://plugins.gradle.org/plugin/com.github.lkishalmi.gatling

```
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find gradle.plugin.com.github.lkishalmi.gradle:gradle-gatling-plugin:0.5.0.
     Searched in the following locations:
         https://plugins.gradle.org/m2/gradle/plugin/com/github/lkishalmi/gradle/gradle-gatling-plugin/0.5.0/gradle-gatling-plugin-0.5.0.pom
         https://plugins.gradle.org/m2/gradle/plugin/com/github/lkishalmi/gradle/gradle-gatling-plugin/0.5.0/gradle-gatling-plugin-0.5.0.jar
     Required by:
```

**Comment by eshepelyuk** [comment] 2017-10-10 13:52
This is a duplication of https://github.com/lkishalmi/gradle-gatling-plugin/issues/43

**Comment by eshepelyuk** [comment] 2017-10-10 20:31
closing as duplicate of #43

**Closed** 2017-10-10 20:32 UTC
